### ISSUE TITLE
conversion error on upgrade from 1.15 to 1.16

### ISSUE THREAD

**Issue by zarrellab** [gettalong/kramdown#476]
An example of the error I get:
`Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/post-name.md': undefined method 'value' for nil:NilClass`
 
Started getting the errors after the update. Jekyll requires ~>1.14. So, builds after the update to 1.16 started failing.

Errors from jekyll build --verbose --trace:
```/Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kramdown-1.16.0/lib/kramdown/parser/gfm.rb:170:in `block in parse_list': undefined method `value' for nil:NilClass (NoMethodError)
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kramdown-1.16.0/lib/kramdown/parser/gfm.rb:168:in `each'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kramdown-1.16.0/lib/kramdown/parser/gfm.rb:168:in `parse_list'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kramdown-1.16.0/lib/kramdown/parser/kramdown.rb:148:in `block (2 levels) in parse_blocks'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kramdown-1.16.0/lib/kramdown/parser/kramdown.rb:146:in `any?'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kramdown-1.16.0/lib/kramdown/parser/kramdown.rb:146:in `block in parse_blocks'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kramdown-1.16.0/lib/kramdown/parser/kramdown.rb:144:in `catch'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kramdown-1.16.0/lib/kramdown/parser/kramdown.rb:144:in `parse_blocks'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kramdown-1.16.0/lib/kramdown/parser/kramdown.rb:89:in `parse'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kramdown-1.16.0/lib/kramdown/parser/gfm.rb:45:in `parse'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kramdown-1.16.0/lib/kramdown/parser/base.rb:69:in `parse'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kramdown-1.16.0/lib/kramdown/document.rb:104:in `initialize'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/converters/markdown/kramdown_parser.rb:41:in `new'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/converters/markdown/kramdown_parser.rb:41:in `convert'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/converters/markdown.rb:77:in `convert'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:98:in `block in convert'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:96:in `each'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:96:in `reduce'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:96:in `convert'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:80:in `render_document'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:62:in `run'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:455:in `block (2 levels) in render_docs'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:453:in `each'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:453:in `block in render_docs'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:452:in `each_value'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:452:in `render_docs'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:192:in `render'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:73:in `process'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/command.rb:28:in `process_site'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:65:in `build'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:36:in `process'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.4.1/bin/jekyll:22:in `load'
	from /Users/user/.rbenv/versions/2.4.1/bin/jekyll:22:in `<main>'```

**Comment by gettalong** [comment]
Fixed with new release 1.16.1!
